# This is a basic workflow to help you get started with Actions

name: Waka Readme

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
  schedule:
    # Runs every Sunday at 16:00 UTC (i.e. Monday 00:00 CST/Beijing time)
    - cron: '0 0 * * *'

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          LOCALE: 'zh'
          SHOW_LINES_OF_CODE: 'True'
          SHOW_TOTAL_CODE_TIME: 'True'
          SHOW_PROFILE_VIEWS: 'False'
          SHOW_COMMIT: 'False'
          SHOW_DAYS_OF_WEEK: 'False'
          SHOW_LANGUAGE: 'False'
          SHOW_OS: 'False'
          SHOW_TIMEZONE: 'False'
          SHOW_EDITORS: 'False'
          SHOW_LANGUAGE_PER_REPO: 'False'
          SHOW_PROJECTS: 'False'
          SHOW_SHORT_INFO: 'False'
          SHOW_LOC_CHART: 'False'
          SHOW_UPDATED_DATE: 'False'
